-- DEFAULT SQD WEB / Supabase schema
-- MVP mode: public demo policies are enabled so the static GitHub Pages frontend can read/write with the anon key.
-- Before production, replace these policies with Supabase Auth based checks.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id text primary key,
  user_id text unique not null,
  name text not null,
  role text,
  avatar text not null default 'SQ',
  avatar_image text not null default '',
  banner_image text not null default '',
  status text not null default 'online',
  bio text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  owner_id text not null references public.profiles(id) on delete cascade,
  text text not null check (char_length(trim(text)) > 0 and char_length(text) <= 280),
  media_attached boolean not null default false,
  tags text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  author_id text not null references public.profiles(id) on delete cascade,
  text text not null check (char_length(trim(text)) > 0 and char_length(text) <= 280),
  created_at timestamptz not null default now()
);

create table if not exists public.post_reactions (
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id text not null references public.profiles(id) on delete cascade,
  type text not null check (type in ('like', 'repost', 'bookmark')),
  created_at timestamptz not null default now(),
  primary key (post_id, user_id, type)
);

create index if not exists posts_created_at_idx on public.posts (created_at desc);
create index if not exists posts_owner_id_idx on public.posts (owner_id);
create index if not exists comments_post_id_idx on public.comments (post_id);
create index if not exists post_reactions_post_id_idx on public.post_reactions (post_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists posts_set_updated_at on public.posts;
create trigger posts_set_updated_at
before update on public.posts
for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.post_reactions enable row level security;

-- Realtime publication for Supabase Realtime subscriptions.
do $$
begin
  alter publication supabase_realtime add table public.posts;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.comments;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.post_reactions;
exception when duplicate_object then null;
end $$;

-- Public demo policies. Good for a free MVP/demo; not safe for a real production community.
drop policy if exists "profiles_select_public" on public.profiles;
create policy "profiles_select_public" on public.profiles for select using (true);

drop policy if exists "profiles_insert_public" on public.profiles;
create policy "profiles_insert_public" on public.profiles for insert with check (true);

drop policy if exists "profiles_update_public" on public.profiles;
create policy "profiles_update_public" on public.profiles for update using (true) with check (true);

drop policy if exists "posts_select_public" on public.posts;
create policy "posts_select_public" on public.posts for select using (true);

drop policy if exists "posts_insert_public" on public.posts;
create policy "posts_insert_public" on public.posts for insert with check (true);

drop policy if exists "posts_update_public" on public.posts;
create policy "posts_update_public" on public.posts for update using (true) with check (true);

drop policy if exists "posts_delete_public" on public.posts;
create policy "posts_delete_public" on public.posts for delete using (true);

drop policy if exists "comments_select_public" on public.comments;
create policy "comments_select_public" on public.comments for select using (true);

drop policy if exists "comments_insert_public" on public.comments;
create policy "comments_insert_public" on public.comments for insert with check (true);

drop policy if exists "comments_delete_public" on public.comments;
create policy "comments_delete_public" on public.comments for delete using (true);

drop policy if exists "post_reactions_select_public" on public.post_reactions;
create policy "post_reactions_select_public" on public.post_reactions for select using (true);

drop policy if exists "post_reactions_insert_public" on public.post_reactions;
create policy "post_reactions_insert_public" on public.post_reactions for insert with check (true);

drop policy if exists "post_reactions_delete_public" on public.post_reactions;
create policy "post_reactions_delete_public" on public.post_reactions for delete using (true);
