-- DEFAULT SQD WEB / Release features
-- Adds real notifications and direct messages. Run after 001_schema.sql and 004_closed_auth.sql.
-- No demo content is created here.

create extension if not exists pgcrypto;

create table if not exists public.direct_conversations (
  id uuid primary key default gen_random_uuid(),
  direct_key text unique,
  created_at timestamptz not null default now()
);

create table if not exists public.direct_conversation_members (
  conversation_id uuid not null references public.direct_conversations(id) on delete cascade,
  user_id text not null references public.profiles(id) on delete cascade,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  primary key (conversation_id, user_id)
);

create table if not exists public.direct_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.direct_conversations(id) on delete cascade,
  sender_id text not null references public.profiles(id) on delete cascade,
  text text not null check (char_length(trim(text)) > 0 and char_length(text) <= 1000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  recipient_id text not null references public.profiles(id) on delete cascade,
  actor_id text references public.profiles(id) on delete set null,
  type text not null check (type in ('comment', 'like', 'repost', 'bookmark', 'message')),
  post_id bigint references public.posts(id) on delete cascade,
  comment_id bigint references public.comments(id) on delete cascade,
  message_id bigint references public.direct_messages(id) on delete cascade,
  text text not null,
  read_at timestamptz,
  dedupe_key text unique,
  created_at timestamptz not null default now()
);

create index if not exists direct_conversation_members_user_idx on public.direct_conversation_members (user_id);
create index if not exists direct_messages_conversation_created_idx on public.direct_messages (conversation_id, created_at desc);
create index if not exists notifications_recipient_created_idx on public.notifications (recipient_id, created_at desc);
create index if not exists notifications_recipient_unread_idx on public.notifications (recipient_id) where read_at is null;

alter table public.direct_conversations enable row level security;
alter table public.direct_conversation_members enable row level security;
alter table public.direct_messages enable row level security;
alter table public.notifications enable row level security;

create or replace function public.is_conversation_member(target_conversation_id uuid, target_user_id text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.direct_conversation_members member
    where member.conversation_id = target_conversation_id
      and member.user_id = target_user_id
  );
$$;


-- Remove old policies from previous iterations, if any.
drop policy if exists "direct_conversations_select_member" on public.direct_conversations;
drop policy if exists "direct_conversations_insert_authenticated" on public.direct_conversations;
drop policy if exists "direct_conversation_members_select_member" on public.direct_conversation_members;
drop policy if exists "direct_conversation_members_insert_member_or_new" on public.direct_conversation_members;
drop policy if exists "direct_conversation_members_update_own" on public.direct_conversation_members;
drop policy if exists "direct_messages_select_member" on public.direct_messages;
drop policy if exists "direct_messages_insert_member" on public.direct_messages;
drop policy if exists "direct_messages_update_own" on public.direct_messages;
drop policy if exists "direct_messages_delete_own" on public.direct_messages;
drop policy if exists "notifications_select_own" on public.notifications;
drop policy if exists "notifications_update_own" on public.notifications;
drop policy if exists "notifications_delete_own" on public.notifications;

create policy "direct_conversations_select_member"
on public.direct_conversations
for select
to authenticated
using (public.is_conversation_member(id, auth.uid()::text));

-- Clients cannot insert conversations directly. Use public.create_direct_conversation(target_user_id).

create policy "direct_conversation_members_select_member"
on public.direct_conversation_members
for select
to authenticated
using (public.is_conversation_member(conversation_id, auth.uid()::text));

-- Clients cannot insert members directly. The RPC below creates exactly 1:1 memberships.

create policy "direct_conversation_members_update_own"
on public.direct_conversation_members
for update
to authenticated
using (user_id = auth.uid()::text)
with check (user_id = auth.uid()::text);

create policy "direct_messages_select_member"
on public.direct_messages
for select
to authenticated
using (public.is_conversation_member(conversation_id, auth.uid()::text));

create policy "direct_messages_insert_member"
on public.direct_messages
for insert
to authenticated
with check (
  sender_id = auth.uid()::text
  and public.is_conversation_member(conversation_id, auth.uid()::text)
);

create policy "direct_messages_update_own"
on public.direct_messages
for update
to authenticated
using (
  sender_id = auth.uid()::text
  and public.is_conversation_member(conversation_id, auth.uid()::text)
)
with check (
  sender_id = auth.uid()::text
  and public.is_conversation_member(conversation_id, auth.uid()::text)
);

create policy "direct_messages_delete_own"
on public.direct_messages
for delete
to authenticated
using (
  sender_id = auth.uid()::text
  and public.is_conversation_member(conversation_id, auth.uid()::text)
);

drop trigger if exists direct_messages_set_updated_at on public.direct_messages;
create trigger direct_messages_set_updated_at
before update on public.direct_messages
for each row execute function public.set_updated_at();


drop policy if exists "post_reactions_update_own" on public.post_reactions;
create policy "post_reactions_update_own"
on public.post_reactions
for update
to authenticated
using (user_id = auth.uid()::text)
with check (user_id = auth.uid()::text);

create policy "notifications_select_own"
on public.notifications
for select
to authenticated
using (recipient_id = auth.uid()::text);

create policy "notifications_update_own"
on public.notifications
for update
to authenticated
using (recipient_id = auth.uid()::text)
with check (recipient_id = auth.uid()::text);

create policy "notifications_delete_own"
on public.notifications
for delete
to authenticated
using (recipient_id = auth.uid()::text);

-- Make table privileges explicit. RLS still controls row access.
grant usage on schema public to authenticated;

revoke insert, update, delete on public.profiles from authenticated;
grant select on public.profiles to authenticated;
grant insert (id, user_id, name, avatar, avatar_image, banner_image, status, bio) on public.profiles to authenticated;
grant update (user_id, name, avatar, avatar_image, banner_image, status, bio) on public.profiles to authenticated;

grant select, insert, update, delete on public.posts to authenticated;
grant select, insert, update, delete on public.comments to authenticated;
grant select, insert, update, delete on public.post_reactions to authenticated;

revoke insert, update, delete on public.direct_conversations from authenticated;
revoke insert, update, delete on public.direct_conversation_members from authenticated;
grant select on public.direct_conversations to authenticated;
grant select on public.direct_conversation_members to authenticated;
grant update (read_at) on public.direct_conversation_members to authenticated;
grant select, insert, update, delete on public.direct_messages to authenticated;

grant select, update, delete on public.notifications to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create or replace function public.safe_create_notification(
  target_recipient_id text,
  target_actor_id text,
  target_type text,
  target_post_id bigint,
  target_comment_id bigint,
  target_message_id bigint,
  target_text text,
  target_dedupe_key text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if target_recipient_id is null or target_recipient_id = target_actor_id then
    return;
  end if;

  insert into public.notifications (
    recipient_id,
    actor_id,
    type,
    post_id,
    comment_id,
    message_id,
    text,
    dedupe_key
  )
  values (
    target_recipient_id,
    target_actor_id,
    target_type,
    target_post_id,
    target_comment_id,
    target_message_id,
    target_text,
    target_dedupe_key
  )
  on conflict (dedupe_key) do update set
    text = excluded.text,
    read_at = null,
    created_at = now();
end;
$$;

revoke all on function public.safe_create_notification(text, text, text, bigint, bigint, bigint, text, text) from public, anon, authenticated;

create or replace function public.notify_post_comment()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  recipient_id text;
  actor_name text;
begin
  select owner_id into recipient_id from public.posts where id = new.post_id;
  select name into actor_name from public.profiles where id = new.author_id;

  perform public.safe_create_notification(
    recipient_id,
    new.author_id,
    'comment',
    new.post_id,
    new.id,
    null,
    coalesce(actor_name, 'Участник') || ' ответил(а) на ваш пост',
    'comment:' || new.id::text
  );

  return new;
end;
$$;

create or replace function public.notify_post_reaction()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  recipient_id text;
  actor_name text;
  action_text text;
begin
  select owner_id into recipient_id from public.posts where id = new.post_id;
  select name into actor_name from public.profiles where id = new.user_id;

  action_text := case new.type
    when 'like' then 'поставил(а) лайк'
    when 'repost' then 'сделал(а) репост'
    when 'bookmark' then 'добавил(а) пост в избранное'
    else 'обновил(а) реакцию'
  end;

  perform public.safe_create_notification(
    recipient_id,
    new.user_id,
    new.type,
    new.post_id,
    null,
    null,
    coalesce(actor_name, 'Участник') || ' ' || action_text,
    'reaction:' || new.type || ':' || new.post_id::text || ':' || new.user_id
  );

  return new;
end;
$$;

create or replace function public.notify_direct_message()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  member_record record;
  actor_name text;
begin
  select name into actor_name from public.profiles where id = new.sender_id;

  for member_record in
    select user_id
    from public.direct_conversation_members
    where conversation_id = new.conversation_id
      and user_id <> new.sender_id
  loop
    perform public.safe_create_notification(
      member_record.user_id,
      new.sender_id,
      'message',
      null,
      null,
      new.id,
      coalesce(actor_name, 'Участник') || ' написал(а) сообщение',
      'message:' || new.id::text || ':' || member_record.user_id
    );
  end loop;

  return new;
end;
$$;

revoke all on function public.notify_post_comment() from public, anon, authenticated;
revoke all on function public.notify_post_reaction() from public, anon, authenticated;
revoke all on function public.notify_direct_message() from public, anon, authenticated;

create or replace function public.enforce_direct_conversation_pair()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if (
    select count(*)
    from public.direct_conversation_members
    where conversation_id = new.conversation_id
  ) > 2 then
    raise exception 'Direct conversations must have exactly two members';
  end if;

  return new;
end;
$$;

revoke all on function public.enforce_direct_conversation_pair() from public, anon, authenticated;

drop trigger if exists direct_conversation_members_enforce_pair on public.direct_conversation_members;
create trigger direct_conversation_members_enforce_pair
after insert on public.direct_conversation_members
for each row execute function public.enforce_direct_conversation_pair();

drop trigger if exists comments_notify_insert on public.comments;
create trigger comments_notify_insert
after insert on public.comments
for each row execute function public.notify_post_comment();

drop trigger if exists post_reactions_notify_insert on public.post_reactions;
create trigger post_reactions_notify_insert
after insert on public.post_reactions
for each row execute function public.notify_post_reaction();

drop trigger if exists direct_messages_notify_insert on public.direct_messages;
create trigger direct_messages_notify_insert
after insert on public.direct_messages
for each row execute function public.notify_direct_message();

-- Realtime tables.
do $$
begin
  alter publication supabase_realtime add table public.notifications;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.direct_conversations;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.direct_conversation_members;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.direct_messages;
exception when duplicate_object then null;
end $$;

-- Atomic direct chat creation used by the frontend. Keeps RLS strict while avoiding insert+select loops.
create or replace function public.create_direct_conversation(target_user_id text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id text;
  conversation_uuid uuid;
  conversation_key text;
begin
  current_user_id := auth.uid()::text;

  if current_user_id is null then
    raise exception 'Not authenticated';
  end if;

  if target_user_id is null or length(trim(target_user_id)) = 0 then
    raise exception 'Target user is required';
  end if;

  if target_user_id = current_user_id then
    raise exception 'Cannot create conversation with yourself';
  end if;

  if not exists (select 1 from public.profiles where id = target_user_id) then
    raise exception 'Target profile does not exist';
  end if;

  conversation_key := case
    when current_user_id < target_user_id then current_user_id || ':' || target_user_id
    else target_user_id || ':' || current_user_id
  end;

  insert into public.direct_conversations (direct_key)
  values (conversation_key)
  on conflict (direct_key) do update
  set direct_key = excluded.direct_key
  returning id into conversation_uuid;

  insert into public.direct_conversation_members (conversation_id, user_id)
  values (conversation_uuid, current_user_id), (conversation_uuid, target_user_id)
  on conflict (conversation_id, user_id) do nothing;

  return conversation_uuid;
end;
$$;

revoke all on function public.create_direct_conversation(text) from public, anon;
grant execute on function public.create_direct_conversation(text) to authenticated;
